import { NextResponse } from "next/server";
import { generateBlogPost } from "@/lib/gemini";
import { supabaseServer } from "@/lib/supabase/server";

const CRON_SECRET = process.env.CRON_SECRET;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

export const dynamic = "force-dynamic";
export const maxDuration = 60;

export async function GET(req: Request) {
  const authHeader = req.headers.get("authorization");
  const secret = authHeader?.replace("Bearer ", "").trim();

  if (!CRON_SECRET || secret !== CRON_SECRET) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  if (!GEMINI_API_KEY) {
    return NextResponse.json(
      { error: "GEMINI_API_KEY not set. Add it in Vercel Environment Variables." },
      { status: 500 }
    );
  }

  try {
    const post = await generateBlogPost();
    if (!post) {
      return NextResponse.json({
        ok: false,
        message: "Gemini could not generate a valid post (or word count < 1500).",
        published: null,
      });
    }

    let slug = post.slug;
    const { data: existing } = await supabaseServer
      .from("posts")
      .select("id")
      .eq("slug", slug)
      .maybeSingle();

    if (existing) {
      slug = `${post.slug}-${Date.now().toString(36)}`;
    }

    const { error: insertError } = await supabaseServer.from("posts").insert({
      title: post.title,
      slug,
      excerpt: post.excerpt,
      content: post.content,
      seo_title: post.seo_title,
      seo_description: post.seo_description,
      featured_image: null,
      category_id: null,
      published: true,
      published_at: new Date().toISOString(),
    });

    if (insertError) {
      console.error("[generate-and-publish] insert error:", insertError);
      return NextResponse.json(
        { error: "Failed to save post", details: insertError.message },
        { status: 500 }
      );
    }

    return NextResponse.json({
      ok: true,
      message: "Post generated by Gemini and published.",
      published: { title: post.title, slug },
    });
  } catch (err) {
    console.error("[generate-and-publish] error:", err);
    return NextResponse.json(
      { error: "Internal error", details: String(err) },
      { status: 500 }
    );
  }
}
