import { NextResponse } from "next/server";
import { generateBlogPost } from "@/lib/gemini";
import { supabaseServer } from "@/lib/supabase/server";

const CRON_SECRET = process.env.CRON_SECRET;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

export const dynamic = "force-dynamic";
export const maxDuration = 60;

export async function GET(req: Request) {
  const authHeader = req.headers.get("authorization");
  const secret = authHeader?.replace("Bearer ", "").trim();

  if (!CRON_SECRET || secret !== CRON_SECRET) {
    console.error("[generate-and-publish] unauthorized: missing/invalid Authorization header");
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  if (!GEMINI_API_KEY) {
    return NextResponse.json(
      { error: "GEMINI_API_KEY not set. Add it in Vercel Environment Variables." },
      { status: 500 }
    );
  }

  try {
    // Gemini generation can occasionally fail due to JSON formatting or short output.
    // Retry a few times so the cron is more reliable day-to-day.
    let post: Awaited<ReturnType<typeof generateBlogPost>> | null = null;
    let lastFailure: unknown = null;
    const attempts = 3;
    for (let i = 1; i <= attempts; i++) {
      const res = await generateBlogPost();
      if (res.ok) {
        post = res;
        break;
      }
      lastFailure = res.failure;
      console.error(`[generate-and-publish] gemini generation failed (attempt ${i}/${attempts})`, res.failure);
    }

    if (!post) {
      // Non-2xx so Vercel Cron shows this run as a failure.
      return NextResponse.json(
        {
          ok: false,
          // Keep both fields for compatibility with older clients/logs.
          message: "Gemini could not generate a valid post (JSON parse failed or word count too low).",
          error: "Gemini could not generate a valid post (JSON parse failed or word count too low).",
          reason: lastFailure ?? null,
          published: null,
        },
        { status: 503 }
      );
    }

    const generated = post.post;
    let slug = generated.slug;
    const { data: existing } = await supabaseServer
      .from("posts")
      .select("id")
      .eq("slug", slug)
      .maybeSingle();

    if (existing) {
      slug = `${generated.slug}-${Date.now().toString(36)}`;
    }

    const { error: insertError } = await supabaseServer.from("posts").insert({
      title: generated.title,
      slug,
      excerpt: generated.excerpt,
      content: generated.content,
      seo_title: generated.seo_title,
      seo_description: generated.seo_description,
      featured_image: null,
      category_id: null,
      published: true,
      published_at: new Date().toISOString(),
    });

    if (insertError) {
      console.error("[generate-and-publish] insert error:", insertError);
      return NextResponse.json(
        { error: "Failed to save post", details: insertError.message },
        { status: 500 }
      );
    }

    return NextResponse.json({
      ok: true,
      message: "Post generated by Gemini and published.",
      published: { title: generated.title, slug },
    });
  } catch (err) {
    console.error("[generate-and-publish] error:", err);
    return NextResponse.json(
      { error: "Internal error", details: String(err) },
      { status: 500 }
    );
  }
}
